// Generated by gencpp from file tutorial_python/multiplier.msg
// DO NOT EDIT!


#ifndef TUTORIAL_PYTHON_MESSAGE_MULTIPLIER_H
#define TUTORIAL_PYTHON_MESSAGE_MULTIPLIER_H

#include <ros/service_traits.h>


#include <tutorial_python/multiplierRequest.h>
#include <tutorial_python/multiplierResponse.h>


namespace tutorial_python
{

struct multiplier
{

typedef multiplierRequest Request;
typedef multiplierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiplier
} // namespace tutorial_python


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial_python::multiplier > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::tutorial_python::multiplier&) { return value(); }
};

template<>
struct DataType< ::tutorial_python::multiplier > {
  static const char* value()
  {
    return "tutorial_python/multiplier";
  }

  static const char* value(const ::tutorial_python::multiplier&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial_python::multiplierRequest> should match
// service_traits::MD5Sum< ::tutorial_python::multiplier >
template<>
struct MD5Sum< ::tutorial_python::multiplierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial_python::multiplier >::value();
  }
  static const char* value(const ::tutorial_python::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial_python::multiplierRequest> should match
// service_traits::DataType< ::tutorial_python::multiplier >
template<>
struct DataType< ::tutorial_python::multiplierRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial_python::multiplier >::value();
  }
  static const char* value(const ::tutorial_python::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial_python::multiplierResponse> should match
// service_traits::MD5Sum< ::tutorial_python::multiplier >
template<>
struct MD5Sum< ::tutorial_python::multiplierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial_python::multiplier >::value();
  }
  static const char* value(const ::tutorial_python::multiplierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial_python::multiplierResponse> should match
// service_traits::DataType< ::tutorial_python::multiplier >
template<>
struct DataType< ::tutorial_python::multiplierResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial_python::multiplier >::value();
  }
  static const char* value(const ::tutorial_python::multiplierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL_PYTHON_MESSAGE_MULTIPLIER_H
