// Generated by gencpp from file tutorial_python/multiplierRequest.msg
// DO NOT EDIT!


#ifndef TUTORIAL_PYTHON_MESSAGE_MULTIPLIERREQUEST_H
#define TUTORIAL_PYTHON_MESSAGE_MULTIPLIERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_python
{
template <class ContainerAllocator>
struct multiplierRequest_
{
  typedef multiplierRequest_<ContainerAllocator> Type;

  multiplierRequest_()
    : a(0)
    , b(0)  {
    }
  multiplierRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::tutorial_python::multiplierRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_python::multiplierRequest_<ContainerAllocator> const> ConstPtr;

}; // struct multiplierRequest_

typedef ::tutorial_python::multiplierRequest_<std::allocator<void> > multiplierRequest;

typedef boost::shared_ptr< ::tutorial_python::multiplierRequest > multiplierRequestPtr;
typedef boost::shared_ptr< ::tutorial_python::multiplierRequest const> multiplierRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_python::multiplierRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_python::multiplierRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_python::multiplierRequest_<ContainerAllocator1> & lhs, const ::tutorial_python::multiplierRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_python::multiplierRequest_<ContainerAllocator1> & lhs, const ::tutorial_python::multiplierRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial_python::multiplierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_python::multiplierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_python::multiplierRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_python::multiplierRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_python::multiplierRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_python::multiplierRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_python::multiplierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef8322123148e475e3e93a1f609b2f70";
  }

  static const char* value(const ::tutorial_python::multiplierRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef8322123148e475ULL;
  static const uint64_t static_value2 = 0xe3e93a1f609b2f70ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_python::multiplierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_python/multiplierRequest";
  }

  static const char* value(const ::tutorial_python::multiplierRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_python::multiplierRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
"int32 b\n"
;
  }

  static const char* value(const ::tutorial_python::multiplierRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_python::multiplierRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct multiplierRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_python::multiplierRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_python::multiplierRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_PYTHON_MESSAGE_MULTIPLIERREQUEST_H
