// Generated by gencpp from file tutorial_python/Position.msg
// DO NOT EDIT!


#ifndef TUTORIAL_PYTHON_MESSAGE_POSITION_H
#define TUTORIAL_PYTHON_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial_python
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : message()
    , x(0.0)
    , y(0.0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : message(_alloc)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::tutorial_python::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial_python::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::tutorial_python::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::tutorial_python::Position > PositionPtr;
typedef boost::shared_ptr< ::tutorial_python::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial_python::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial_python::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial_python::Position_<ContainerAllocator1> & lhs, const ::tutorial_python::Position_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial_python::Position_<ContainerAllocator1> & lhs, const ::tutorial_python::Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial_python

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tutorial_python::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial_python::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_python::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial_python::Position_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_python::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial_python::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial_python::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e1f88ae0dc8c54957ce388602e32426";
  }

  static const char* value(const ::tutorial_python::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e1f88ae0dc8c549ULL;
  static const uint64_t static_value2 = 0x57ce388602e32426ULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial_python::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial_python/Position";
  }

  static const char* value(const ::tutorial_python::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial_python::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::tutorial_python::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial_python::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial_python::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial_python::Position_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_PYTHON_MESSAGE_POSITION_H
