// Generated by gencpp from file line_msg/LinePoint.msg
// DO NOT EDIT!


#ifndef LINE_MSG_MESSAGE_LINEPOINT_H
#define LINE_MSG_MESSAGE_LINEPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>

namespace line_msg
{
template <class ContainerAllocator>
struct LinePoint_
{
  typedef LinePoint_<ContainerAllocator> Type;

  LinePoint_()
    : header()
    , startx()
    , starty()
    , endx()
    , endy()  {
    }
  LinePoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , startx(_alloc)
    , starty(_alloc)
    , endx(_alloc)
    , endy(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _startx_type;
  _startx_type startx;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _starty_type;
  _starty_type starty;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _endx_type;
  _endx_type endx;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _endy_type;
  _endy_type endy;





  typedef boost::shared_ptr< ::line_msg::LinePoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::line_msg::LinePoint_<ContainerAllocator> const> ConstPtr;

}; // struct LinePoint_

typedef ::line_msg::LinePoint_<std::allocator<void> > LinePoint;

typedef boost::shared_ptr< ::line_msg::LinePoint > LinePointPtr;
typedef boost::shared_ptr< ::line_msg::LinePoint const> LinePointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::line_msg::LinePoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::line_msg::LinePoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::line_msg::LinePoint_<ContainerAllocator1> & lhs, const ::line_msg::LinePoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.startx == rhs.startx &&
    lhs.starty == rhs.starty &&
    lhs.endx == rhs.endx &&
    lhs.endy == rhs.endy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::line_msg::LinePoint_<ContainerAllocator1> & lhs, const ::line_msg::LinePoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace line_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::line_msg::LinePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::line_msg::LinePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_msg::LinePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::line_msg::LinePoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_msg::LinePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::line_msg::LinePoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::line_msg::LinePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1aadf4bb8a6f95a32166f6069d5187f4";
  }

  static const char* value(const ::line_msg::LinePoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1aadf4bb8a6f95a3ULL;
  static const uint64_t static_value2 = 0x2166f6069d5187f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::line_msg::LinePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "line_msg/LinePoint";
  }

  static const char* value(const ::line_msg::LinePoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::line_msg::LinePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/Float32MultiArray startx\n"
"std_msgs/Float32MultiArray starty\n"
"std_msgs/Float32MultiArray endx\n"
"std_msgs/Float32MultiArray endy\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::line_msg::LinePoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::line_msg::LinePoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.startx);
      stream.next(m.starty);
      stream.next(m.endx);
      stream.next(m.endy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinePoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::line_msg::LinePoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::line_msg::LinePoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "startx: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.startx);
    s << indent << "starty: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.starty);
    s << indent << "endx: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.endx);
    s << indent << "endy: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.endy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LINE_MSG_MESSAGE_LINEPOINT_H
