// Generated by gencpp from file yolov5_ros/yolov5_data.msg
// DO NOT EDIT!


#ifndef YOLOV5_ROS_MESSAGE_YOLOV5_DATA_H
#define YOLOV5_ROS_MESSAGE_YOLOV5_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float32MultiArray.h>
#include <std_msgs/Float32MultiArray.h>

namespace yolov5_ros
{
template <class ContainerAllocator>
struct yolov5_data_
{
  typedef yolov5_data_<ContainerAllocator> Type;

  yolov5_data_()
    : header()
    , yolo_box_data()
    , object_depth_data()
    , line_data()  {
    }
  yolov5_data_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , yolo_box_data(_alloc)
    , object_depth_data(_alloc)
    , line_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _yolo_box_data_type;
  _yolo_box_data_type yolo_box_data;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _object_depth_data_type;
  _object_depth_data_type object_depth_data;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _line_data_type;
  _line_data_type line_data;





  typedef boost::shared_ptr< ::yolov5_ros::yolov5_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov5_ros::yolov5_data_<ContainerAllocator> const> ConstPtr;

}; // struct yolov5_data_

typedef ::yolov5_ros::yolov5_data_<std::allocator<void> > yolov5_data;

typedef boost::shared_ptr< ::yolov5_ros::yolov5_data > yolov5_dataPtr;
typedef boost::shared_ptr< ::yolov5_ros::yolov5_data const> yolov5_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov5_ros::yolov5_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov5_ros::yolov5_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov5_ros::yolov5_data_<ContainerAllocator1> & lhs, const ::yolov5_ros::yolov5_data_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.yolo_box_data == rhs.yolo_box_data &&
    lhs.object_depth_data == rhs.object_depth_data &&
    lhs.line_data == rhs.line_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov5_ros::yolov5_data_<ContainerAllocator1> & lhs, const ::yolov5_ros::yolov5_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov5_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov5_ros::yolov5_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov5_ros::yolov5_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_ros::yolov5_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov5_ros::yolov5_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_ros::yolov5_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov5_ros::yolov5_data_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov5_ros::yolov5_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bc2c0993d921554a14c584cfa00945e";
  }

  static const char* value(const ::yolov5_ros::yolov5_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bc2c0993d921554ULL;
  static const uint64_t static_value2 = 0xa14c584cfa00945eULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov5_ros::yolov5_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov5_ros/yolov5_data";
  }

  static const char* value(const ::yolov5_ros::yolov5_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov5_ros::yolov5_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"std_msgs/Float32MultiArray yolo_box_data\n"
"std_msgs/Float32MultiArray object_depth_data\n"
"float32[] line_data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::yolov5_ros::yolov5_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov5_ros::yolov5_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.yolo_box_data);
      stream.next(m.object_depth_data);
      stream.next(m.line_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yolov5_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov5_ros::yolov5_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov5_ros::yolov5_data_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "yolo_box_data: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.yolo_box_data);
    s << indent << "object_depth_data: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.object_depth_data);
    s << indent << "line_data[]" << std::endl;
    for (size_t i = 0; i < v.line_data.size(); ++i)
    {
      s << indent << "  line_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.line_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV5_ROS_MESSAGE_YOLOV5_DATA_H
